name: Build base vLLM image

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["*.*.*"]
    paths:
      - ".github/workflows/vllm-base.yaml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/vllm-base.yaml"

jobs:
  publish-docker:
    permissions:
      contents: write
      actions: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platforms: "linux/amd64"
            image_tag: cuda12.8
            cuda_version: "12.8"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout vLLM
        run: |
          git clone https://github.com/vllm-project/vllm.git && cd vllm
      - name: Maximize Docker Build Space
        uses: gpustack/.github/.github/actions/maximize-docker-build-space@main
        with:
          deep-clean: true
          root-reserve-mb: 20480
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v9.2.2
          platforms: "arm64"
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login DockerHub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_PASSWORD }}
      - name: Package
        uses: docker/build-push-action@v5
        id: package
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ github.workspace }}/vllm/docker/Dockerfile
          context: ${{ github.workspace }}/vllm
          platforms: ${{ matrix.platforms }}
          tags: ${{ matrix.image_tag }}
          provenance: true
          sbom: true
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
